export component VerticalCarousel inherits FocusScope {
    in-out property <int> current-item: 0;
    in property <int> count: 2;
    property <length> swipe-padding: 5px;

    sgr := SwipeGestureHandler {
        handle-swipe-down: current-item > 0;
        handle-swipe-up: current-item < root.count - 1;
        swiped => {
            if self.current-position.y > self.pressed-position.y + root.swipe-padding {
                current-item -= 1;
            } else if self.current-position.y < self.pressed-position.y - root.swipe-padding {
                current-item += 1;
            }
        }

        VerticalLayout {
            property <length> position: - current-item * root.height;
            property <length> swipe-offset;
            animate position {
                duration: 200ms;
                easing: ease-in-out;
            }
            y: position + swipe-offset;

            @children
        }
    }
}
