[package]
name = "rusty-bucket-face"
categories = ["embedded", "no-std"]
version = "0.1.0"
authors = ["Ruslan Sovinskyy <ruslan.sovinskyy@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gc9a01-rs = { git = "https://github.com/IniterWorker/gc9a01.git", branch = "master", features = [
    'graphics',
] }
embedded-graphics-core = "0.4.0"

esp-backtrace = { version = "0.14.1", features = [
    "esp32s3",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-hal = { version = "0.20.1", features = [
    "log",
    "esp32s3",
    "embedded-hal",
    "async",
] }
esp-println = { version = "0.11.0", features = ["esp32s3", "log"] }
log = { version = "0.4.21" }
esp-alloc = { version = "0.4.0" }
embedded-io = "0.6.1"
esp-wifi = { version = "0.9.1", features = [
    "esp32s3",
    "phy-enable-usb",
    "utils",
    "wifi-default",
] }
embedded-hal = "1.0.0"
embedded-hal-bus = "0.2.0"
embedded-hal-async = "1.0.0"

slint = { version = "1.8.0", default-features = false, features = [
    "compat-1-2",
    "unsafe-single-threaded",
    "libm",
    "renderer-software",
] }

esp-hal-embassy = { version = "0.3.0", features = ["esp32s3"] }
embassy-time = { version = "0.3.2", features = ["generic-queue-8"] }
embassy-executor = { version = "0.6.0", features = ["task-arena-size-262144"] }
static_cell = "2.1.0"
xtensa-lx-rt = { version = "0.17.1", features = [
    "esp32s3",
    "float-save-restore",
] }


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false

[build-dependencies]
slint-build = "1.8.0"
