import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { AppFonts } from "./common.slint";

export component BoostPage inherits Window {
    in property <int> manifold-pressure-reading: 103;

    VerticalBox {
        padding: 0;
        spacing: 0;
        height: 100%;
        padding-left: 20px;

        HorizontalBox {
            padding-right: 16px;
            alignment: center;

            Text {
                // See https://github.com/slint-ui/slint/issues/5822
                // width: 150px;

                text: root.manifold-pressure-reading;
                vertical-alignment: bottom;
                horizontal-alignment: right;
                color: white;
                font-family: AppFonts.gauges-font-name;
                font-size: 100px;
                height: 100%;
            }

            Text {
                text: "kPa";
                vertical-alignment: bottom;
                font-size: 42px;
                height: 100%;
            }
        }
    }
}
