import { AboutSlint, Button, VerticalBox, Palette } from "std-widgets.slint";
export component AppWindow inherits Window {
    width: 240px;
    height: 240px;
    background: blue;
    VerticalBox {
        alignment: start;
        label := Text {
            text: "Hello World!";
            font-size: 24px;
            horizontal-alignment: center;
        }

        AboutSlint {
            preferred-height: 150px;
        }

        HorizontalLayout {
            Rectangle {
                background: red;
                Button {
                    text: "OK!";
                }
            }
        }
    }
}
