import { AboutSlint, Button, VerticalBox, Palette, ScrollView, HorizontalBox } from "std-widgets.slint";
import { DisplayLimits, AppFonts } from "./common.slint";
import { O2Page } from "o2_page.slint";

export component AppWindow inherits Window {
    width: 240px;
    height: 240px;
    padding: 0;

    Image {
        source: @image-url("./assets/background_1.jpg");
    }

    DisplayLimits {
        VerticalBox {
            padding: 0;
            alignment: center;

            O2Page { }
        }
    }
}
